import {
  forwardRef,
  Inject,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model, Types } from 'mongoose';
import * as path from 'node:path';
import { ConfigService } from '@nestjs/config';
import { MedicalDocument, AiFindings } from './schemas/medical-document.schema';
import { AiService } from '../ai/ai.service';
import { VerificationService } from '../verification/verification.service';
import { PatientsService } from '../patients/patients.service';
import { NotificationsService } from '../notifications/notifications.service';
import { idFilter } from '../../common/mongoose.util';

@Injectable()
export class DocumentsService {
  constructor(
    @InjectModel(MedicalDocument.name)
    private readonly documentModel: Model<MedicalDocument>,
    private readonly config: ConfigService,
    private readonly aiService: AiService,
    @Inject(forwardRef(() => VerificationService))
    private readonly verificationService: VerificationService,
    private readonly patientsService: PatientsService,
    private readonly notificationsService: NotificationsService,
  ) {}

  uploadDir(): string {
    return this.config.get<string>('UPLOAD_DIR', 'uploads');
  }

  async create(patientId: string | Types.ObjectId, file: Express.Multer.File) {
    const uploadDir = this.uploadDir();
    const filePath = path.join(uploadDir, file.filename);
    return this.documentModel.create({
      patient: patientId,
      filename: file.originalname,
      mimeType: file.mimetype,
      size: file.size,
      filePath,
    });
  }

  async analyze(id: string, language = 'en', patientId?: string) {
    const doc = await this.findOwned(id, patientId);

    if (doc.mimeType?.startsWith('application/pdf')) {
      doc.aiFindings = {
        docType: 'other',
        text: 'PDF documents require manual review.',
        summary:
          'This is a PDF document. AI reading of PDFs is limited; a doctor will review it.',
        abnormalFindings: [],
        recommendations: [
          'Please upload a clear image (JPG/PNG) of the report for AI analysis.',
        ],
        confidence: 0,
        disclaimer:
          'This analysis was generated by AI and has NOT been verified by a doctor.',
        language,
      };
    } else {
      const findings = (await this.aiService.analyzeDocument(
        doc.filePath,
        language,
      )) as unknown as AiFindings;
      doc.aiFindings = { ...findings, language };
    }

    doc.status = 'awaiting-doctor';
    await doc.save();

    await this.verificationService.create({
      taskType: 'document',
      refId: doc._id,
      patient: doc.patient,
      aiOutput: doc.aiFindings as unknown as Record<string, unknown>,
    });

    return doc;
  }

  async approve(
    id: string | Types.ObjectId,
    doctor: string | Types.ObjectId,
    comment?: string,
  ) {
    return this.review(id, doctor, 'approved', comment);
  }

  async reject(
    id: string | Types.ObjectId,
    doctor: string | Types.ObjectId,
    comment?: string,
  ) {
    return this.review(id, doctor, 'rejected', comment);
  }

  private async review(
    id: string | Types.ObjectId,
    doctor: string | Types.ObjectId,
    decision: 'approved' | 'rejected',
    comment?: string,
  ) {
    const doc = await this.documentModel
      .findByIdAndUpdate(
        id,
        {
          status: decision,
          doctorReview: { doctor, decision, comment, reviewedAt: new Date() },
        },
        { new: true },
      )
      .exec();
    if (!doc) return null;

    const patient = await this.patientsService
      .findById(doc.patient)
      .catch(() => null);
    if (patient) {
      await this.notificationsService.create({
        user: patient.user,
        title:
          decision === 'approved'
            ? 'Your report has been reviewed'
            : 'Your report needs attention',
        body:
          comment?.trim() ||
          (decision === 'approved'
            ? `A doctor reviewed "${doc.filename}" and confirmed the AI findings.`
            : `A doctor could not confirm the AI findings for "${doc.filename}". Please book a consultation.`),
        type: 'document',
        ref: { documentId: doc._id.toString() },
      });
    }

    return doc;
  }

  async listForPatient(patientId: string | Types.ObjectId) {
    return this.documentModel
      .find(idFilter('patient', patientId))
      .sort({ createdAt: -1 })
      .lean()
      .exec();
  }

  async listAll(filter: Record<string, unknown> = {}) {
    return this.documentModel
      .find(filter)
      .sort({ createdAt: -1 })
      .populate('patient')
      .lean()
      .exec();
  }

  async findById(id: string | Types.ObjectId) {
    const doc = await this.documentModel.findById(id).exec();
    if (!doc) throw new NotFoundException('Document not found');
    return doc;
  }

  /**
   * Same as findById but refuses documents belonging to another patient.
   * Pass no patientId (doctors) to skip the ownership check.
   */
  async findOwned(id: string | Types.ObjectId, patientId?: string) {
    const doc = await this.findById(id);
    if (patientId && doc.patient.toString() !== patientId) {
      // 404, not 403 - don't confirm the document exists.
      throw new NotFoundException('Document not found');
    }
    return doc;
  }
}
